"""
Django settings for avee_foods project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from decimal import Decimal
import os

import dj_database_url
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-*q=mhbtmxdt34^0pp38w@@fc+y1g_1el1!255!ktl%&e(*lc%$"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "aveefoods.in",
    "www.aveefoods.in",
    "avee-foods.onrender.com",
    "localhost",
    "127.0.0.1",
]

# Render terminates TLS, so POST forms need the https origins trusted
CSRF_TRUSTED_ORIGINS = [
    "https://aveefoods.in",
    "https://www.aveefoods.in",
    "https://avee-foods.onrender.com",
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "website",
    "dashboard",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "avee_foods.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "website.context_processors.storefront",
            ],
        },
    },
]

WSGI_APPLICATION = "avee_foods.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Postgres in production (Render sets DATABASE_URL), sqlite locally.
# sslmode only applies to Postgres -- sqlite rejects it as a connect kwarg.
_DATABASE_URL = os.environ.get("DATABASE_URL", "")

DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        ssl_require=_DATABASE_URL.startswith(("postgres://", "postgresql://")),
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Project-wide static assets (logo, favicons) shared by both apps
STATICFILES_DIRS = [BASE_DIR / "static"]

# WhiteNoise serves the collected static files under gunicorn
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"
    },
}

# Media files (User uploads)
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Login URL for authentication
LOGIN_URL = "dashboard:login"
LOGIN_REDIRECT_URL = "dashboard:home"

# Keep guest carts alive for a month so a customer can come back and check out
SESSION_COOKIE_AGE = 60 * 60 * 24 * 30
SESSION_SAVE_EVERY_REQUEST = True

# ---------------------------------------------------------------------------
# Storefront configuration
# ---------------------------------------------------------------------------
# Everything the checkout, the UPI page and the footer need. Change the values
# here -- no template edits required.
STORE = {
    "name": "Avee Foods",
    "shipping_fee": Decimal("60.00"),
    "free_shipping_above": Decimal("1000.00"),
    # Cash on Delivery was withdrawn -- every order is prepaid by UPI.
    "cod_available": False,
    # UPI collect details. `upi_id` must be the VPA money should land in.
    "upi_id": "suriya16696@oksbi",
    "upi_payee": "Suriya Venkatesan",
    "upi_enabled": True,
    "support_phone": "+91 70105 46105",
    "whatsapp": "917010546105",
    "support_email": "aveeoils@gmail.com",
    # Social links in the mobile menu. Blank means "hide that icon", so drop a
    # full https:// URL in as each channel goes live.
    "facebook": "",
    "instagram": "",
    "youtube": "",
    "address": "157/2, Chettiyar Street, Pudur, Periyamoor Post, Gingee Tk, Villupuram DT 604151",
    "delivery_days": 4,
    "gst_number": "33ABCDE1234F1Z5",
    "fssai_number": "22426354000527",
}


# Email
# https://docs.djangoproject.com/en/5.1/topics/email/
#
# Order confirmations and tracking codes go out over Gmail SMTP. Gmail needs an
# App Password (not the account password), set as EMAIL_HOST_PASSWORD in the
# environment. Without it we fall back to printing mail to the console, so
# local development and a half-configured deploy still work rather than 500.

COMPANY_EMAIL = "aveeoils@gmail.com"

# Absolute base for links inside emails, where there is no request to build from
SITE_URL = os.environ.get("SITE_URL", "https://www.aveefoods.in").rstrip("/")

EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", COMPANY_EMAIL)
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")

if EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_USE_TLS = True
EMAIL_TIMEOUT = 20

DEFAULT_FROM_EMAIL = f'Avee Foods <{EMAIL_HOST_USER}>'
SERVER_EMAIL = EMAIL_HOST_USER

# Tracking codes emailed to customers
ORDER_OTP_LENGTH = 6
ORDER_OTP_TTL_SECONDS = 10 * 60
ORDER_OTP_MAX_ATTEMPTS = 5


os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'avee_foods.settings')