# Generated by Django 5.2.17 on 2026-08-15 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_category_alter_foodproduct_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodproduct",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="website.category",
            ),
        ),
    ]
