# Generated by Django 5.2.17 on 2026-08-15 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_backfill_product_slugs"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Photo"), ("video", "Video")],
                        default="image",
                        max_length=5,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="home_banner/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                [
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "webp",
                                    "gif",
                                    "avif",
                                    "mp4",
                                    "webm",
                                    "ogg",
                                    "mov",
                                    "m4v",
                                ]
                            )
                        ],
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=150)),
                ("subtitle", models.CharField(blank=True, max_length=250)),
                ("button_text", models.CharField(blank=True, max_length=60)),
                (
                    "button_url",
                    models.CharField(
                        blank=True,
                        help_text="Where the button goes, e.g. /products/",
                        max_length=250,
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Photos only — how long this slide stays on screen.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Only ticked items appear on the home page.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Home banner",
                "verbose_name_plural": "Home banners",
                "ordering": ["display_order", "id"],
            },
        ),
    ]
