# Generated by Django 5.2.17 on 2026-08-15 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_homebanner"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, max_length=140)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="subcategories/"
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="website.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Subcategories",
                "ordering": ["display_order", "name"],
                "unique_together": {("category", "name"), ("category", "slug")},
            },
        ),
        migrations.AddField(
            model_name="foodproduct",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                help_text="Must belong to the category chosen above.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="website.subcategory",
            ),
        ),
    ]
