# Generated by Django 5.2.17 on 2026-08-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_subcategory_foodproduct_subcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("cod", "Cash on Delivery"), ("upi", "UPI / GPay / PhonePe")],
                default="upi",
                max_length=10,
            ),
        ),
    ]
